name: Unogram Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup VS environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Show structure
      shell: cmd
      run: |
        dir /s Telegram\build\prepare
        dir build.ps1

    - name: Patch prepare script
      shell: powershell
      run: |
        $path = "Telegram\build\prepare\win.bat"
        $content = Get-Content $path -Raw
        $content = $content -replace "call %FullScriptPath% %1 %2 %3 %4 %5", "call %FullScriptPath% -DDESKTOP_APP_DISABLE_BREAKPAD=ON -DDESKTOP_APP_DISABLE_OPENAL=ON %1 %2 %3 %4 %5"
        Set-Content $path $content -Encoding ASCII
        Get-Content $path

    - name: Prepare libraries
      shell: cmd
      run: Telegram\build\prepare\win.bat

    - name: Build
      shell: cmd
      run: .\build.ps1

    - name: Upload result
      uses: actions/upload-artifact@v4
      with:
        name: Unogram-Debug
        path: |
          out/Debug/Telegram.exe
          out/Debug/*.dll
        retention-days: 30
