name: Unogram Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Show files
        shell: pwsh
        run: |
          Get-ChildItem -Force
          Get-ChildItem -Recurse -Filter build.ps1

      - name: Build
        shell: pwsh
        run: |
          .\build.ps1
